name: ci

on: 
  pull_request:
  push:
    branches: [main]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        run: npx markdownlint-cli2 "**/*.md"
        